version: '3'

services:
      mysql:
         image: mysql:5.7
         restart: on-failure
         environment:
           MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
           MYSQL_DATABASE: ${MYSQL_DATABASE}
        
      nginx:
        image: nginx:1.19.0-alpine
        restart: on-failure
        volumes:
          - './backend/public:/usr/src/app'
          - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
          - '${NGINX_PORT}:80'
        depends_on:
         - php
         - react
      
      adminer:
       image: adminer
       restart: on-failure
       ports:
         - '${ADMINER_PORT}:8080'

      php:
        build:
          context: .
          dockerfile: docker/php/Dockerfile
        volumes:
          - './backend/:/usr/src/app'
        restart: on-failure
        env_file:
          - .env
        user: 1000:1000

      react:
        stdin_open: true
        environment:
          - CHOKIDAR_USEPOLLING=true
        build:
          dockerfile: docker/react/Dockerfile
          context: .
        volumes:
          - /app/node_modules
          - ./react:/app
