export const TOTAL_CUSTOMER_REQUESTED = 'TOTAL_CUSTOMER_REQUESTED';
export const TOTAL_CUSTOMER_SUCCEEDED = 'TOTAL_CUSTOMER_SUCCEEDED';
export const TOTAL_CUSTOMER_FAILED = 'TOTAL_CUSTOMER_FAILED';

export const TOTAL_ORDER_REQUESTED = 'TOTAL_ORDER_REQUESTED';
export const TOTAL_ORDER_SUCCEEDED = 'TOTAL_ORDER_SUCCEEDED';
export const TOTAL_ORDER_FAILED = 'TOTAL_ORDER_FAILED';

export const TOTAL_REVENUE_REQUESTED = 'TOTAL_REVENUE_REQUESTED';
export const TOTAL_REVENUE_SUCCEEDED = 'TOTAL_REVENUE_SUCCEEDED';
export const TOTAL_REVENUE_FAILED = 'TOTAL_REVENUE_FAILED';

export const TIME_FRAME_REQUESTED = 'TIME_FRAME_REQUESTED';
export const TIME_FRAME_SUCCEEDED = 'TIME_FRAME_SUCCEEDED';
export const TIME_FRAME_FAILED = 'TIME_FRAME_FAILED';

export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
